In [8]:
import numpy as np

In [9]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


# Array Calculations and Array Indexing

In [10]:
A = np.array([1,2,5])

In [11]:
B = np.array([3,6,9])

## Ex 1

In [12]:
print(A+B)

[ 4  8 14]


In [13]:
print(A*B)

[ 3 12 45]


## Ex 2

In [14]:
def mean(array):
    return (sum(array)/len(array))

In [15]:
mean(A)

2.6666666666666665

## Ex 3

In [16]:
def var(array):
    return sum(((array - mean(array))**2)/len(array))

In [17]:
def stdev(array):
    return var(array)**(1/2)

In [18]:
stdev(A)

1.699673171197595

## Ex 4

In [19]:
a = arange(128)

In [20]:
def reshaper(array):
    return array.reshape((int(len(a)/2)),2)

In [21]:
def bothsums(array):
    return numpy.sum(reshaper(array), axis=0, dtype=None, out=None, keepdims=False)

In [22]:
def unevensum(array):
    return (bothsums(array))[0]

In [23]:
unevensum(a)

4032

## Ex 5

In [24]:
a = arange(1024)

In [25]:
def firsthalf(array):
    return np.array(array[0:(int(len(array)/2))])

In [26]:
firsthalf(a)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

## Ex 6

In [27]:
def chunk22_42(array):
    return np.array(array[22:43])

In [28]:
chunk22_42(a)

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42])

## Ex 7

In [29]:
C = np.array([0.2,7.1,3.4])

In [31]:
# def multiplier(array, intarray):
    
# Do not understand exercise

## Ex 8

In [32]:
def reverse(array):
    return(array[::-1])

In [33]:
reverse(A)

array([5, 2, 1])

## Ex 9

In [34]:
b = np.random.rand(128)

In [35]:
def lessthanhalf(array):
    return array[(find(array <= 0.5))]


In [36]:
lessthanhalf(b)

array([ 0.21358154,  0.25671564,  0.23797175,  0.25639318,  0.26442052,
        0.28556781,  0.27144909,  0.32262833,  0.1887024 ,  0.28841537,
        0.19993962,  0.05486919,  0.09403579,  0.28000153,  0.48817085,
        0.24370497,  0.20494103,  0.24489797,  0.32947411,  0.03519294,
        0.12470837,  0.30627052,  0.23628113,  0.41992246,  0.30402256,
        0.14290561,  0.13902083,  0.32396907,  0.4336276 ,  0.0222524 ,
        0.1050434 ,  0.25232692,  0.31969   ,  0.33335772,  0.49512541,
        0.42715963,  0.44480702,  0.36108594,  0.33350455,  0.36063082,
        0.05138107,  0.17560923,  0.11544244,  0.25871218,  0.0907155 ,
        0.41325171,  0.11485095,  0.17809487,  0.27137817,  0.08854919,
        0.01847444,  0.4785967 ,  0.38130876,  0.24725714,  0.0680921 ,
        0.2676134 ,  0.21356974,  0.05770196,  0.49693742,  0.02619532,
        0.39412391,  0.04664909,  0.05279884,  0.18539463,  0.37415115,
        0.27103099,  0.48630341,  0.13612554,  0.09283453])

# Two dimensional data arrays

## Ex 1

In [37]:
import numpy as np

In [42]:
a_p1 = np.array([[1],[0],[0],[1],[0],[1]])

In [43]:
a_pfeatures1 = (np.array([3,1,5,2,4,6,3,2,1,2,3,5,7,1,4,2,5,7])).reshape(6,3)

In [103]:
a_p1 = (np.array([0,1,1,0,0,1]))

In [ ]:
# 0 = bananas
# 1 = apples

In [104]:
a_pfeatures1

array([[3, 1, 5],
       [2, 4, 6],
       [3, 2, 1],
       [2, 3, 5],
       [7, 1, 4],
       [2, 5, 7]])

In [129]:
# mass, circum, area

In [105]:
a_p1

array([0, 1, 1, 0, 0, 1])

In [45]:
def ex_row(a_pfeat,i):
    return a_pfeat[i,:]
    

In [46]:
ex_row(a_pfeatures1,2)

array([3, 2, 1])

## Ex 2

In [47]:
def ex_column(a_pfeat,j):
    return a_pfeat[:,j]

In [48]:
ex_column(a_pfeatures1,1)

array([1, 4, 2, 3, 1, 5])

## Ex 3

In [49]:
def mean(array):
    return (sum(array)/len(array))

In [50]:
def columnmean(a_pfeat,j):
    return mean(ex_column(a_pfeat,j))

In [51]:
columnmean(a_pfeatures1,1)

2.6666666666666665

In [84]:
def meansarray(a_pfeat):
    return np.array([[mean(ex_column(a_pfeat,0))],[mean(ex_column(a_pfeat,1))],[mean(ex_column(a_pfeat,2))]])

In [85]:
meansarray(a_pfeatures1)

array([[ 3.16666667],
       [ 2.66666667],
       [ 4.66666667]])

In [120]:
def meansmatrix(a_pfeat):
    return np.transpose(np.repeat((np.array(meansarray(a_pfeat))),(len(a_pfeat)),axis=-1))

In [121]:
meansmatrix(a_pfeatures1)

array([[ 3.16666667,  2.66666667,  4.66666667],
       [ 3.16666667,  2.66666667,  4.66666667],
       [ 3.16666667,  2.66666667,  4.66666667],
       [ 3.16666667,  2.66666667,  4.66666667],
       [ 3.16666667,  2.66666667,  4.66666667],
       [ 3.16666667,  2.66666667,  4.66666667]])

## Ex 4

In [93]:
def minmean(a_pfeat):
    return a_pfeat-meansmatrix(a_pfeat)

In [94]:
minmean(a_pfeatures1)

array([[-0.16666667, -1.66666667,  0.33333333],
       [-1.16666667,  1.33333333,  1.33333333],
       [-0.16666667, -0.66666667, -3.66666667],
       [-1.16666667,  0.33333333,  0.33333333],
       [ 3.83333333, -1.66666667, -0.66666667],
       [-1.16666667,  2.33333333,  2.33333333]])

## Ex 5

In [106]:
def appleselect(a_p,a_pfeat):
    return np.compress(a_p, a_pfeat, axis=0)

In [107]:
appleselect(a_p1,a_pfeatures1)

array([[2, 4, 6],
       [3, 2, 1],
       [2, 5, 7]])

In [115]:
def applecolumnmean(a_p,a_pfeat,j):
    return mean(ex_column(appleselect(a_p,a_pfeat),j))

In [116]:
applecolumnmean(a_p1,a_pfeatures1,0)

2.3333333333333335

In [118]:
def applemeansarray(a_p,a_pfeat):
    return np.array([[mean(ex_column(appleselect(a_p,a_pfeat),0))],[mean(ex_column(appleselect(a_p,a_pfeat),1))],
                     [mean(ex_column(appleselect(a_p,a_pfeat),2))]])
    

In [119]:
applemeansarray(a_p1,a_pfeatures1)

array([[ 2.33333333],
       [ 3.66666667],
       [ 4.66666667]])

In [123]:
def applemeansmatrix(a_p,a_pfeat):
    return np.transpose(np.repeat((np.array(meansarray(appleselect(a_p,a_pfeat)))),(len(appleselect(a_p,a_pfeat))),axis=-1))

In [124]:
applemeansmatrix(a_p1,a_pfeatures1)

array([[ 2.33333333,  3.66666667,  4.66666667],
       [ 2.33333333,  3.66666667,  4.66666667],
       [ 2.33333333,  3.66666667,  4.66666667]])

## Ex 6

In [136]:
def largestmass(a_pfeat):
    return ex_row(a_pfeat,(np.argmax(ex_column(a_pfeat,0))))
    

In [137]:
largestmass(a_pfeatures1)

array([7, 1, 4])

## Ex 7

In [138]:
# ? Do not understand exercise

# Tricks with Arrays

## Ex 1